"""
Step 67 - BUY/SELL live precision sweep across trade definitions.

Checks whether the 80% precision goal is reachable under any practical target
definition already generated by step 52:
  stop buffer: 5, 8, 12, 20 pips
  R target: 1.0, 1.5, 2.0
  horizon: 60m, 120m

Uses the step-64 side-level feature set and HGB only for speed.
"""

from __future__ import annotations

import importlib.util
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score


BASE = "/home/cmake/Vector/research"
HELPER = f"{BASE}/64_buy_sell_precision_refine.py"
PANEL = f"{BASE}/EURUSD_M5_FULL_PANEL.csv.gz"
PIVOTS = f"{BASE}/EURUSD_M5_ZZLINES_D12_Dev5_Back3_FULL_AVAILABLE_pivot_map.csv"
GREEDY = f"{BASE}/zzlines_greedy_cover_summary.csv"
OUTCOMES = f"{BASE}/zzlines_pivot_entry_outcomes.csv"

OUT_QUALITY = f"{BASE}/zzlines_buy_sell_target_sweep_quality.csv"
OUT_REPORT = f"{BASE}/ZZLINES_BUY_SELL_TARGET_SWEEP.md"

DEV_START = "2025-06-02"
DEV_END = "2026-02-28 23:59:59"
OOS_START = "2026-03-01"
OOS_END = "2026-06-01 23:55:00"
ENTRY_OFFSETS = [0, 1, 2]

SIDE_CLASSES = {
    "BUY": ["HL", "LL"],
    "SELL": ["HH", "LH"],
}


def load_helper():
    spec = importlib.util.spec_from_file_location("step64", HELPER)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def target(panel: pd.DataFrame, outcomes: pd.DataFrame, side: str, stop: int, rr: float, horizon: int) -> np.ndarray:
    y = np.zeros(len(panel), dtype=bool)
    pos = pd.Series(np.arange(len(panel)), index=panel.index)
    good = outcomes[
        outcomes["label"].isin(SIDE_CLASSES[side])
        & outcomes["entry_offset"].isin(ENTRY_OFFSETS)
        & outcomes["tradable"]
        & outcomes["stop_buffer_pips"].eq(stop)
        & outcomes["rr_target"].eq(rr)
        & outcomes["horizon_bars"].eq(horizon)
        & outcomes["entry_time"].isin(pos.index)
    ].copy()
    if not good.empty:
        y[pos.loc[good["entry_time"]].values.astype(int)] = True
    return y


def main():
    step64 = load_helper()
    print("loading...")
    panel = pd.read_csv(PANEL, index_col=0, parse_dates=True).loc[DEV_START:OOS_END].copy()
    pivots = pd.read_csv(PIVOTS, parse_dates=["pivot_time"])
    rules = pd.read_csv(GREEDY)
    outcomes = pd.read_csv(OUTCOMES, parse_dates=["pivot_time", "entry_time", "hit_time"])
    outcomes = outcomes[(outcomes["entry_time"] >= DEV_START) & (outcomes["entry_time"] <= OOS_END)].copy()

    print("adding features...")
    panel = step64.add_sr_features(panel, pivots)
    panel = step64.add_temporal_features(panel)
    feats = step64.numeric_features(panel)
    X = step64.prep_X(panel, feats)

    dev_mask = (panel.index >= pd.Timestamp(DEV_START)) & (panel.index <= pd.Timestamp(DEV_END))
    oos_mask = (panel.index >= pd.Timestamp(OOS_START)) & (panel.index <= pd.Timestamp(OOS_END))
    thresholds = [0.50, 0.60, 0.70, 0.75, 0.80, 0.85, 0.88, 0.90, 0.92, 0.94, 0.96, 0.98, 0.99]
    modes = ["all_bars", "first_cross", "run_peak"]
    rows = []

    for side, classes in SIDE_CLASSES.items():
        s1 = step64.stage1_mask(panel, rules, classes)
        train_idx = np.where(s1 & dev_mask)[0]
        test_idx = np.where(s1 & oos_mask)[0]
        for stop in [5, 8, 12, 20]:
            for rr in [1.0, 1.5, 2.0]:
                for horizon in [12, 24]:
                    y = target(panel, outcomes, side, stop, rr, horizon)
                    ytr = y[train_idx].astype(int)
                    yte = y[test_idx].astype(int)
                    if ytr.sum() < 50 or yte.sum() < 10:
                        continue
                    model = HistGradientBoostingClassifier(
                        max_iter=600,
                        learning_rate=0.035,
                        max_leaf_nodes=24,
                        max_depth=6,
                        min_samples_leaf=35,
                        l2_regularization=0.25,
                        early_stopping=True,
                        validation_fraction=0.15,
                        n_iter_no_change=50,
                        random_state=42,
                    )
                    spw = (len(ytr) - ytr.sum()) / max(ytr.sum(), 1)
                    sw = np.where(ytr == 1, spw, 1.0)
                    model.fit(X.iloc[train_idx], ytr, sample_weight=sw)
                    prob = model.predict_proba(X.iloc[test_idx])[:, 1]
                    auc = roc_auc_score(yte, prob)
                    for mode in modes:
                        for th in thresholds:
                            sig = step64.signal_mask(prob, test_idx, th, mode)
                            signals = int(sig.sum())
                            hits = int((sig & (yte == 1)).sum())
                            precision = hits / signals if signals else 0.0
                            recall = hits / int(yte.sum()) if int(yte.sum()) else 0.0
                            rows.append({
                                "side": side,
                                "stop_buffer_pips": stop,
                                "rr_target": rr,
                                "horizon_bars": horizon,
                                "horizon_minutes": horizon * 5,
                                "mode": mode,
                                "threshold": th,
                                "auc": auc,
                                "train_pos": int(ytr.sum()),
                                "oos_pos": int(yte.sum()),
                                "signals": signals,
                                "hits": hits,
                                "precision": precision,
                                "recall": recall,
                            })
                    best = pd.DataFrame(rows)
                    best = best[
                        best["side"].eq(side)
                        & best["stop_buffer_pips"].eq(stop)
                        & best["rr_target"].eq(rr)
                        & best["horizon_bars"].eq(horizon)
                        & (best["signals"] >= 5)
                    ].sort_values(["precision", "hits", "recall"], ascending=False)
                    if not best.empty:
                        r = best.iloc[0]
                        print(
                            f"{side} stop={stop} rr={rr} h={horizon*5}m: "
                            f"best {100*r['precision']:.1f}% signals={int(r['signals'])} hits={int(r['hits'])} AUC={auc:.3f}"
                        )

    quality = pd.DataFrame(rows)
    quality.to_csv(OUT_QUALITY, index=False, float_format="%.6f")

    lines = ["# ZZLines BUY/SELL Target Sweep", ""]
    lines.append("This checks whether 80% OOS precision is reachable by changing stop/R/horizon target definition.")
    lines += ["", "## Best OOS Precision With >=5 Signals", ""]
    for side in SIDE_CLASSES:
        sub = quality[(quality["side"].eq(side)) & (quality["signals"] >= 5)]
        if sub.empty:
            lines.append(f"- {side}: no result")
            continue
        r = sub.sort_values(["precision", "hits", "recall"], ascending=False).iloc[0]
        status = "PASS" if r["precision"] >= 0.80 else "MISS"
        lines.append(
            f"- {side}: `{status}`, stop `{int(r['stop_buffer_pips'])}`, R `{r['rr_target']:.1f}`, "
            f"horizon `{int(r['horizon_minutes'])}m`, mode `{r['mode']}`, threshold `{r['threshold']:.2f}`, "
            f"signals `{int(r['signals'])}`, hits `{int(r['hits'])}`, precision `{100*r['precision']:.1f}%`, "
            f"recall `{100*r['recall']:.1f}%`, AUC `{r['auc']:.3f}`"
        )
    lines += ["", "## Output", "", f"- `{OUT_QUALITY}`"]
    with open(OUT_REPORT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nsaved: {OUT_QUALITY}")
    print(f"saved: {OUT_REPORT}")


if __name__ == "__main__":
    main()
